import os
import sqlite3
from pathlib import Path


DATABASE_URL = os.getenv("DATABASE_URL")
DB_PATH = Path("data/paradise.db")


class CursorWrapper:
    def __init__(self, cursor):
        self.cursor = cursor
        self.lastrowid = None

    def fetchone(self):
        row = self.cursor.fetchone()
        return row

    def fetchall(self):
        return self.cursor.fetchall()

    @property
    def rowcount(self):
        return self.cursor.rowcount


class PostgreSQLConnection:
    def __init__(self, connection):
        self.connection = connection

    def execute(self, sql, params=()):
        sql = sql.replace("?", "%s")

        # PostgreSQL needs RETURNING id for the order ID.
        if (
            sql.strip().upper().startswith("INSERT INTO ORDERS")
            and "RETURNING" not in sql.upper()
        ):
            sql = sql.rstrip().rstrip(";") + " RETURNING id"

        cursor = self.connection.cursor()
        cursor.execute(sql, params)

        wrapper = CursorWrapper(cursor)

        if sql.strip().upper().startswith("INSERT INTO ORDERS"):
            row = cursor.fetchone()
            if row:
                wrapper.lastrowid = row[0]

        return wrapper

    def commit(self):
        self.connection.commit()

    def rollback(self):
        self.connection.rollback()

    def close(self):
        self.connection.close()


def get_db():
    if DATABASE_URL:
        try:
            import psycopg
        except ImportError as error:
            raise RuntimeError(
                "PostgreSQL is configured but the psycopg package is missing."
            ) from error

        connection = psycopg.connect(DATABASE_URL)
        connection.autocommit = False

        return PostgreSQLConnection(connection)

    DB_PATH.parent.mkdir(exist_ok=True)

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    return conn


def init_db():
    conn = get_db()

    if DATABASE_URL:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS menu_items (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                description TEXT,
                price DOUBLE PRECISION NOT NULL,
                available INTEGER DEFAULT 1
            )
        """)

        conn.execute("""
            CREATE TABLE IF NOT EXISTS orders (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_name TEXT NOT NULL,
                phone TEXT NOT NULL,
                address TEXT,
                order_type TEXT DEFAULT 'DELIVERY',
                notes TEXT,
                payment_method TEXT DEFAULT 'CASH',
                payment_status TEXT DEFAULT 'UNPAID',
                total DOUBLE PRECISION NOT NULL,
                status TEXT DEFAULT 'PENDING',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        conn.execute("""
            CREATE TABLE IF NOT EXISTS order_items (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id INTEGER NOT NULL,
                menu_item_id INTEGER NOT NULL,
                quantity INTEGER NOT NULL,
                price DOUBLE PRECISION NOT NULL,
                FOREIGN KEY(order_id) REFERENCES orders(id),
                FOREIGN KEY(menu_item_id) REFERENCES menu_items(id)
            )
        """)

    else:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS menu_items (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                description TEXT,
                price REAL NOT NULL,
                available INTEGER DEFAULT 1
            )
        """)

        conn.execute("""
            CREATE TABLE IF NOT EXISTS orders (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                customer_name TEXT NOT NULL,
                phone TEXT NOT NULL,
                address TEXT,
                order_type TEXT DEFAULT 'DELIVERY',
                notes TEXT,
                payment_method TEXT DEFAULT 'CASH',
                payment_status TEXT DEFAULT 'UNPAID',
                total REAL NOT NULL,
                status TEXT DEFAULT 'PENDING',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        conn.execute("""
            CREATE TABLE IF NOT EXISTS order_items (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                order_id INTEGER NOT NULL,
                menu_item_id INTEGER NOT NULL,
                quantity INTEGER NOT NULL,
                price REAL NOT NULL,
                FOREIGN KEY(order_id) REFERENCES orders(id),
                FOREIGN KEY(menu_item_id) REFERENCES menu_items(id)
            )
        """)

        columns = {
            "address": "TEXT",
            "order_type": "TEXT DEFAULT 'DELIVERY'",
            "notes": "TEXT",
            "payment_method": "TEXT DEFAULT 'CASH'",
            "payment_status": "TEXT DEFAULT 'UNPAID'"
        }

        existing_columns = {
            row["name"]
            for row in conn.execute(
                "PRAGMA table_info(orders)"
            ).fetchall()
        }

        for column, definition in columns.items():
            if column not in existing_columns:
                conn.execute(
                    f"ALTER TABLE orders ADD COLUMN {column} {definition}"
                )

    conn.commit()
    conn.close()


if __name__ == "__main__":
    init_db()
    print("Paradise Food Hub database initialized.")
